create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table companies add constraint FKc00tikiew5ac81ey8xj0oagc4 foreign key (username) references users (username);
alter table professors add constraint FK9xli6d17fqdg6lehqs61hnwep foreign key (username) references users (username);
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table companies add constraint FKc00tikiew5ac81ey8xj0oagc4 foreign key (username) references users (username);
alter table professors add constraint FK9xli6d17fqdg6lehqs61hnwep foreign key (username) references users (username);
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table companies add constraint FKc00tikiew5ac81ey8xj0oagc4 foreign key (username) references users (username);
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table companies add constraint FKc00tikiew5ac81ey8xj0oagc4 foreign key (username) references users (username);
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table companies add constraint FKc00tikiew5ac81ey8xj0oagc4 foreign key (username) references users (username);
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table companies add constraint FKc00tikiew5ac81ey8xj0oagc4 foreign key (username) references users (username);
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
