create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table evaluations (effectiveness integer, efficiency integer, evaluation_id integer not null auto_increment, motivation integer, traineeship_position_id integer, evaluation_type enum ('COMPANY','SUPERVISOR'), primary key (evaluation_id)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (average_grade float(53), looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table traineeship_positions (from_date date, id integer not null auto_increment, is_assigned bit, passfail_grade bit, to_date date, company_username varchar(255), description varchar(255), professor_username varchar(255), skills varchar(255), student_logbook varchar(255), student_username varchar(255), title varchar(255), topics varchar(255), primary key (id)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table traineeship_positions add constraint UKn3fkum6nkooq2vnvo39q4hj3i unique (student_username);
alter table evaluations add constraint FKjfg2ljdel0aag3eeavkhfylx4 foreign key (traineeship_position_id) references traineeship_positions (id);
alter table traineeship_positions add constraint FKfl2owxe774oc2ualv0fru6foj foreign key (company_username) references companies (username);
alter table traineeship_positions add constraint FKglgumg4coluwti21ca3w1a527 foreign key (student_username) references students (username);
alter table traineeship_positions add constraint FKbkc1owjs06fqilfglt83sw7iy foreign key (professor_username) references professors (username);create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table evaluations (effectiveness integer, efficiency integer, evaluation_id integer not null auto_increment, motivation integer, traineeship_position_id integer, evaluation_type enum ('COMPANY','SUPERVISOR'), primary key (evaluation_id)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (average_grade float(53), looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table traineeship_positions (from_date date, id integer not null auto_increment, is_assigned bit, passfail_grade bit, to_date date, company_username varchar(255), description varchar(255), professor_username varchar(255), skills varchar(255), student_logbook varchar(255), student_username varchar(255), title varchar(255), topics varchar(255), primary key (id)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table traineeship_positions add constraint UKn3fkum6nkooq2vnvo39q4hj3i unique (student_username);
alter table evaluations add constraint FKjfg2ljdel0aag3eeavkhfylx4 foreign key (traineeship_position_id) references traineeship_positions (id);
alter table traineeship_positions add constraint FKfl2owxe774oc2ualv0fru6foj foreign key (company_username) references companies (username);
alter table traineeship_positions add constraint FKglgumg4coluwti21ca3w1a527 foreign key (student_username) references students (username);
alter table traineeship_positions add constraint FKbkc1owjs06fqilfglt83sw7iy foreign key (professor_username) references professors (username);
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table evaluations (effectiveness integer, efficiency integer, evaluation_id integer not null auto_increment, motivation integer, traineeship_position_id integer, evaluation_type enum ('COMPANY','SUPERVISOR'), primary key (evaluation_id)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (average_grade float(53), looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table traineeship_positions (from_date date, id integer not null auto_increment, is_assigned bit, passfail_grade bit, to_date date, company_username varchar(255), description varchar(255), professor_username varchar(255), skills varchar(255), student_logbook varchar(255), student_username varchar(255), title varchar(255), topics varchar(255), primary key (id)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table traineeship_positions add constraint UKn3fkum6nkooq2vnvo39q4hj3i unique (student_username);
alter table evaluations add constraint FKjfg2ljdel0aag3eeavkhfylx4 foreign key (traineeship_position_id) references traineeship_positions (id);
alter table traineeship_positions add constraint FKfl2owxe774oc2ualv0fru6foj foreign key (company_username) references companies (username);
alter table traineeship_positions add constraint FKglgumg4coluwti21ca3w1a527 foreign key (student_username) references students (username);
alter table traineeship_positions add constraint FKbkc1owjs06fqilfglt83sw7iy foreign key (professor_username) references professors (username);
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table evaluations (effectiveness integer, efficiency integer, evaluation_id integer not null auto_increment, motivation integer, traineeship_position_id integer, evaluation_type enum ('COMPANY','SUPERVISOR'), primary key (evaluation_id)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (average_grade float(53), looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table traineeship_positions (from_date date, id integer not null auto_increment, is_assigned bit, passfail_grade bit, to_date date, company_username varchar(255), description varchar(255), professor_username varchar(255), skills varchar(255), student_logbook varchar(255), student_username varchar(255), title varchar(255), topics varchar(255), primary key (id)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table traineeship_positions add constraint UKn3fkum6nkooq2vnvo39q4hj3i unique (student_username);
alter table evaluations add constraint FKjfg2ljdel0aag3eeavkhfylx4 foreign key (traineeship_position_id) references traineeship_positions (id);
alter table traineeship_positions add constraint FKfl2owxe774oc2ualv0fru6foj foreign key (company_username) references companies (username);
alter table traineeship_positions add constraint FKglgumg4coluwti21ca3w1a527 foreign key (student_username) references students (username);
alter table traineeship_positions add constraint FKbkc1owjs06fqilfglt83sw7iy foreign key (professor_username) references professors (username);
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table evaluations (effectiveness integer, efficiency integer, evaluation_id integer not null auto_increment, motivation integer, traineeship_position_id integer, evaluation_type enum ('COMPANY','SUPERVISOR'), primary key (evaluation_id)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (average_grade float(53), looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table traineeship_positions (from_date date, id integer not null auto_increment, is_assigned bit, passfail_grade bit, to_date date, company_username varchar(255), description varchar(255), professor_username varchar(255), skills varchar(255), student_logbook varchar(255), student_username varchar(255), title varchar(255), topics varchar(255), primary key (id)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table traineeship_positions add constraint UKn3fkum6nkooq2vnvo39q4hj3i unique (student_username);
alter table evaluations add constraint FKjfg2ljdel0aag3eeavkhfylx4 foreign key (traineeship_position_id) references traineeship_positions (id);
alter table traineeship_positions add constraint FKfl2owxe774oc2ualv0fru6foj foreign key (company_username) references companies (username);
alter table traineeship_positions add constraint FKglgumg4coluwti21ca3w1a527 foreign key (student_username) references students (username);
alter table traineeship_positions add constraint FKbkc1owjs06fqilfglt83sw7iy foreign key (professor_username) references professors (username);
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table evaluations (effectiveness integer, efficiency integer, evaluation_id integer not null auto_increment, motivation integer, traineeship_position_id integer, evaluation_type enum ('COMPANY','SUPERVISOR'), primary key (evaluation_id)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (average_grade float(53), looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table traineeship_positions (from_date date, id integer not null auto_increment, is_assigned bit, passfail_grade bit, to_date date, company_username varchar(255), description varchar(255), professor_username varchar(255), skills varchar(255), student_logbook varchar(255), student_username varchar(255), title varchar(255), topics varchar(255), primary key (id)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table traineeship_positions add constraint UKn3fkum6nkooq2vnvo39q4hj3i unique (student_username);
alter table evaluations add constraint FKjfg2ljdel0aag3eeavkhfylx4 foreign key (traineeship_position_id) references traineeship_positions (id);
alter table traineeship_positions add constraint FKfl2owxe774oc2ualv0fru6foj foreign key (company_username) references companies (username);
alter table traineeship_positions add constraint FKglgumg4coluwti21ca3w1a527 foreign key (student_username) references students (username);
alter table traineeship_positions add constraint FKbkc1owjs06fqilfglt83sw7iy foreign key (professor_username) references professors (username);
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table evaluations (effectiveness integer, efficiency integer, evaluation_id integer not null auto_increment, motivation integer, traineeship_position_id integer, evaluation_type enum ('COMPANY','SUPERVISOR'), primary key (evaluation_id)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (average_grade float(53), looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table traineeship_positions (from_date date, id integer not null auto_increment, is_assigned bit, passfail_grade bit, to_date date, company_username varchar(255), description varchar(255), professor_username varchar(255), skills varchar(255), student_logbook varchar(255), student_username varchar(255), title varchar(255), topics varchar(255), primary key (id)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table traineeship_positions add constraint UKn3fkum6nkooq2vnvo39q4hj3i unique (student_username);
alter table evaluations add constraint FKjfg2ljdel0aag3eeavkhfylx4 foreign key (traineeship_position_id) references traineeship_positions (id);
alter table traineeship_positions add constraint FKfl2owxe774oc2ualv0fru6foj foreign key (company_username) references companies (username);
alter table traineeship_positions add constraint FKglgumg4coluwti21ca3w1a527 foreign key (student_username) references students (username);
alter table traineeship_positions add constraint FKbkc1owjs06fqilfglt83sw7iy foreign key (professor_username) references professors (username);
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table evaluations (effectiveness integer, efficiency integer, evaluation_id integer not null auto_increment, motivation integer, traineeship_position_id integer, evaluation_type enum ('COMPANY','SUPERVISOR'), primary key (evaluation_id)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (average_grade float(53), looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table traineeship_positions (from_date date, id integer not null auto_increment, is_assigned bit, passfail_grade bit, to_date date, company_username varchar(255), description varchar(255), professor_username varchar(255), skills varchar(255), student_logbook varchar(255), student_username varchar(255), title varchar(255), topics varchar(255), primary key (id)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table traineeship_positions add constraint UKn3fkum6nkooq2vnvo39q4hj3i unique (student_username);
alter table evaluations add constraint FKjfg2ljdel0aag3eeavkhfylx4 foreign key (traineeship_position_id) references traineeship_positions (id);
alter table traineeship_positions add constraint FKfl2owxe774oc2ualv0fru6foj foreign key (company_username) references companies (username);
alter table traineeship_positions add constraint FKglgumg4coluwti21ca3w1a527 foreign key (student_username) references students (username);
alter table traineeship_positions add constraint FKbkc1owjs06fqilfglt83sw7iy foreign key (professor_username) references professors (username);
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table evaluations (effectiveness integer, efficiency integer, evaluation_id integer not null auto_increment, motivation integer, traineeship_position_id integer, evaluation_type enum ('COMPANY','SUPERVISOR'), primary key (evaluation_id)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (average_grade float(53), looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table traineeship_positions (from_date date, id integer not null auto_increment, is_assigned bit, passfail_grade bit, to_date date, company_username varchar(255), description varchar(255), professor_username varchar(255), skills varchar(255), student_logbook varchar(255), student_username varchar(255), title varchar(255), topics varchar(255), primary key (id)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table traineeship_positions add constraint UKn3fkum6nkooq2vnvo39q4hj3i unique (student_username);
alter table evaluations add constraint FKjfg2ljdel0aag3eeavkhfylx4 foreign key (traineeship_position_id) references traineeship_positions (id);
alter table traineeship_positions add constraint FKfl2owxe774oc2ualv0fru6foj foreign key (company_username) references companies (username);
alter table traineeship_positions add constraint FKglgumg4coluwti21ca3w1a527 foreign key (student_username) references students (username);
alter table traineeship_positions add constraint FKbkc1owjs06fqilfglt83sw7iy foreign key (professor_username) references professors (username);
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table evaluations (effectiveness integer, efficiency integer, evaluation_id integer not null auto_increment, motivation integer, traineeship_position_id integer, evaluation_type enum ('COMPANY','SUPERVISOR'), primary key (evaluation_id)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (average_grade float(53), looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table traineeship_positions (from_date date, id integer not null auto_increment, is_assigned bit, passfail_grade bit, to_date date, company_username varchar(255), description varchar(255), professor_username varchar(255), skills varchar(255), student_logbook varchar(255), student_username varchar(255), title varchar(255), topics varchar(255), primary key (id)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table traineeship_positions add constraint UKn3fkum6nkooq2vnvo39q4hj3i unique (student_username);
alter table evaluations add constraint FKjfg2ljdel0aag3eeavkhfylx4 foreign key (traineeship_position_id) references traineeship_positions (id);
alter table traineeship_positions add constraint FKfl2owxe774oc2ualv0fru6foj foreign key (company_username) references companies (username);
alter table traineeship_positions add constraint FKglgumg4coluwti21ca3w1a527 foreign key (student_username) references students (username);
alter table traineeship_positions add constraint FKbkc1owjs06fqilfglt83sw7iy foreign key (professor_username) references professors (username);
create table companies (company_name varchar(255), location varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table evaluations (effectiveness integer, efficiency integer, evaluation_id integer not null auto_increment, motivation integer, traineeship_position_id integer, evaluation_type enum ('COMPANY','SUPERVISOR'), primary key (evaluation_id)) engine=InnoDB;
create table professors (fullname varchar(255), interests varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table students (average_grade float(53), looking_for_traineeship bit, fullname varchar(255), interests varchar(255), preferred_location varchar(255), skills varchar(255), university_id varchar(255), username varchar(255) not null, primary key (username)) engine=InnoDB;
create table traineeship_positions (from_date date, id integer not null auto_increment, is_assigned bit, passfail_grade bit, to_date date, company_username varchar(255), description varchar(255), professor_username varchar(255), skills varchar(255), student_logbook varchar(255), student_username varchar(255), title varchar(255), topics varchar(255), primary key (id)) engine=InnoDB;
create table users (password varchar(255), username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE_MEMBER'), primary key (username)) engine=InnoDB;
alter table traineeship_positions add constraint UKn3fkum6nkooq2vnvo39q4hj3i unique (student_username);
alter table evaluations add constraint FKjfg2ljdel0aag3eeavkhfylx4 foreign key (traineeship_position_id) references traineeship_positions (id);
alter table traineeship_positions add constraint FKfl2owxe774oc2ualv0fru6foj foreign key (company_username) references companies (username);
alter table traineeship_positions add constraint FKglgumg4coluwti21ca3w1a527 foreign key (student_username) references students (username);
alter table traineeship_positions add constraint FKbkc1owjs06fqilfglt83sw7iy foreign key (professor_username) references professors (username);
